### PR TITLE
Clean branch

### PR DESCRIPTION
**Pull request by duembgen**
This is the branch which will have the clean version of the code.
I put all the code and tests in unused_code and unused_tests, and then imported only what was necessary for PublicDatasets (in fact it was quite a lot)

Some things I tried to make consistent:
- remove the python shebang when modules are not scripts (not 100% sure if this is good practice)
- remove the `__main__` part from modules that are not used as scripts, and moved the contents to tests or to related scripts. 
- save everything in figures/ or results/ (depending on if they are plots or data, respectively)
- use """ not ''' for docstrings and long comments 
- Use NotImplementedError wherever it applies (e.g. call function with a solver option that does not exist)
- Use the correct order of import blocks, and alphabetical order within each block. 
```
standard python (e.g. math, sys, time)

systemwide standard libraries (e.g. numpy, scipy, pandas)

our own libraries (e.g. pylocus)

modules from within the project (e.g. trajectory)
```

Some open questions: 
- do we want to have above instructions in GUIDELINES?
- are we keeping semidef relaxation stuff? in fact it still runs, but not sure if it is confusing / useful

### CODE REVIEW

**Comment by micha7a** [comment]
> * remove the python shebang when modules are not scripts (not 100% sure if this is good practice)
> * remove the `__main__` part from modules that are not used as scripts, and moved the contents to tests or to related scripts.
The two together make sense to me :) 

> * Use NotImplementedError wherever it applies (e.g. call function with a solver option that does not exist)
The way I understand it, the `NotImplementError` is used either for functions that are under development (as in "not yet implemented") or for abstract classes.

For a wrong option, like a non-existent solver, I'd raise `ValueError`

> * do we want to have above instructions in GUIDELINES?
Why not :) 
> * are we keeping semidef relaxation stuff? in fact it still runs, but not sure if it is confusing / useful
What is less work :D If we keep it, it would be good to have an example

And I agree with everything else :)

**Comment by duembgen** [comment]
Makes sense, thanks! Your understanding of NotImplementedError is probably more correct so I'll change to ValueErrors where adequate.

**Comment by duembgen** [comment]
@micha7a I am done cleaning up on my side, for now! It is up to you to merge this and work on a new branch, or to also add your changes to this branch.

**Comment by duembgen** [comment]
(I did not put the instructions in Guidelines yet, I can still do it later if we think it is useful. And I did not remove the semidef relaxation functions, since we have tests for them which are working, so it might be useful at some point if we want to reuse this).

**Comment by duembgen** [comment]
Update: need to also check that we can still use the scripts which are now in the scripts folder to regenerate the results.

**Comment by micha7a** [comment]
A silly question, what about `plotting_backup`? In the GenerateAllFigures, two `_old` functions are used, and their new counterparts (without `_old`) are not used at all in our code, so I could just replace the new functions with the old ones, but I think you wanted to clean that up? For me, it is ok to just to replace them.

**Comment by micha7a** [comment]
Also, I'll remove the unused stuff, OK? Or there are some specific things that you want to keep?

**Comment by duembgen** [comment]
> A silly question, what about `plotting_backup`? In the GenerateAllFigures, two `_old` functions are used, and their new counterparts (without `_old`) are not used at all in our code, so I could just replace the new functions with the old ones, but I think you wanted to clean that up? For me, it is ok to just to replace them.

The problem with these functions it they mix a lot of processing with plotting, which I don't find good practice. I think I actually wrote new functions that fix this issue, but didn't look into how to exactly replace these _old functions yet. I will try to fix this today. 

Regarding unused stuff, I only think keeping semidefinite programming might be interesting, the rest that can be removed in my opinion.

**Comment by duembgen** [comment]
@micha7a I fixed the README and removed some more files in results that are not used anymore. There are some folders there which I am not sure are useful, feel free to remove them if you also don't need them. Worse case those can be regenerated

**Pull request merged**
